Fix env vars in e2e test

diff --git a/.github/actions/go-e2e/action.yaml b/.github/actions/go-e2e/action.yaml
--- a/.github/actions/go-e2e/action.yaml
+++ b/.github/actions/go-e2e/action.yaml
@@ -21,7 +21,7 @@ inputs:
     description: 'TUF server hostname'
     required: false
     default: 'tuf.myrhtas'
-  tsa_hostname:
+  tsa_host:
     description: 'TSA server url'
     required: false
     default: 'tsa.myrhtas'
@@ -37,6 +37,10 @@ inputs:
     description: 'OIDC provider url'
     required: false
     default: 'http://dex-idp:5556/dex'
+  oidc_client_secret:
+    description: 'OIDC provider client secret'
+    required: false
+    default: 'ZXhhbXBsZS1hcHAtc2VjcmV0'
   go_version:
     description: 'Go version'
     required: true
@@ -71,18 +75,41 @@ runs:
       run: |
         sudo bash -c "source vm-testing/test/extract_root_cert.sh; extractRootCert ${{ inputs.rekor_host }} /usr/local/share/ca-certificates/myrhtas.crt"
         sudo update-ca-certificates
+    - name: Resolve OIDC TOKEN
+      shell: bash
+      run: |
+        AUTHTOKEN="$(curl -Lis "http://${{ inputs.oidc_host }}:5556/dex/auth/mock?client_id=example-app&scope=openid%20email&redirect_uri=http://${{ inputs.oidc_host }}:5556/callback&response_type=code" | grep -oP "code=\K[^&]+")"
 
+        if [ -z "${AUTHTOKEN}" ]; then
+          echo "Error: Unable to fetch authorization code."
+          exit 1
+        fi
+
+        TOKEN="$(curl -s -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code" -d "code=${AUTHTOKEN}" -d "redirect_uri=http://${{ inputs.oidc_host }}:5556/callback" -d "client_id=example-app" -d "client_secret=${{ inputs.oidc_client_secret }}" "http://${{ inputs.oidc_host }}:5556/dex/token" | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p')"
+        
+        if [ -z "${TOKEN}" ]; then
+          echo "Error: Unable to fetch access code."
+          exit 1
+        fi
+        
+        echo "OIDC_TOKEN=$TOKEN" >> $GITHUB_ENV
     - name: Run e2e
       shell: bash
       env:
-        SIGSTORE_OIDC_ISSUER: ${{ inputs.oidc_url }}
+        OIDC_ISSUER_URL: ${{ inputs.oidc_url }}
+        OIDC_CLIENT_ID: example-app
+        OIDC_USER: "kilgore"
+        OIDC_USER_DOMAIN: "kilgore.trout"
         KEYKLOAK_REALM: example-app
         CLI_STRATEGY: cli_server
         CLI_SERVER_URL: "https://${{ inputs.cli_server_host }}"
         FULCIO_URL: "https://${{ inputs.fulcio_host }}"
         REKOR_URL: "https://${{ inputs.rekor_host }}"
+        REKOR_UI_URL: "https://${{ inputs.rekor_search_host }}"
         TUF_URL: "https://${{ inputs.tuf_host }}"
-        TSA_URL: "https://:${{ inputs.tsa_hostname }}"
+        TSA_URL: "https://${{ inputs.tsa_host }}/api/v1/timestamp"
       run: |
         cd e2e
-        go test -v ./test/...
+        source ./tas-env-variables.sh
+        # exclude UI tests 
+        go test -v $(go list ./test/... | grep -v rekorsearchui)
